name: Update Calendar Files

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */4 * * *'  # Adjust the schedule as necessary
  workflow_run:
    workflows: ["Deploy Hugo Site"]
    types:
      - completed
      
jobs:
  build-environment:
    name: Build environment
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Checkout gh-pages branch
        uses: actions/checkout@v4
        with:
          ref: gh-pages  # Specify to checkout the gh-pages branch
          path: gh-pages

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install
        working-directory: .github/scripts

  process-calendar:
    name: Process ICS Files
    runs-on: ubuntu-latest
    steps:
      - name: Run script to update calendar files
        run: npm start --action
        working-directory: .github/scripts
        env:
          ICS_URL: ${{ secrets.ICS_URL }}

  merge-changes:
    name: Merge Changes
    runs-on: ubuntu-latest
    steps:
      - name: Commit and push if there are changes
        run: |
          cd gh-pages
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git add calendar.ics ical/calendar.json
          git commit -m "Update calendar files" -a || echo "No changes to commit"
          git push origin gh-pages